import { useEffect, useState } from 'react'
import AppLayout from '../components/AppLayout'
import { dashboardService } from '../services/dashboardService'
import { workflowService } from '../services/workflowService'

type SessionItem = {
  id: string
  title: string
  scheduled_date: string
  status: string
  meeting_link?: string
  hybrid_status?: string | null
  latex_compatible?: boolean | null
  meeting_link_valid?: boolean | null
}

function TechnicalModeratorDashboard() {
  const [loading, setLoading] = useState(true)
  const [errorMessage, setErrorMessage] = useState('')
  const [data, setData] = useState<any>(null)

  const [busyId, setBusyId] = useState<string | null>(null)
  const [meetingLinkById, setMeetingLinkById] = useState<Record<string, string>>({})
  const [latexCompatibleById, setLatexCompatibleById] = useState<Record<string, boolean>>({})
  const [hybridStatusById, setHybridStatusById] = useState<Record<string, string>>({})
  const [materialsUrlById, setMaterialsUrlById] = useState<Record<string, string>>({})
  const [issueTypeById, setIssueTypeById] = useState<Record<string, string>>({})
  const [issueDescriptionById, setIssueDescriptionById] = useState<Record<string, string>>({})

  const refresh = async () => {
    setLoading(true)
    setErrorMessage('')
    try {
      const res = await dashboardService.getTechnicalModerator()
      setData(res.data)
    } catch (e: any) {
      setErrorMessage(e?.response?.data?.detail || 'Failed to load technical moderator dashboard.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    refresh()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const sessions = (data?.todays_sessions?.items ?? []) as SessionItem[]

  const handleMeetingLink = async (seminarId: string) => {
    const meetingLink = meetingLinkById[seminarId] ?? ''
    if (!meetingLink.trim()) {
      setErrorMessage('meeting_link is required.')
      return
    }
    setBusyId(seminarId)
    setErrorMessage('')
    try {
      await workflowService.updateMeetingLink(seminarId, meetingLink, hybridStatusById[seminarId], 'Generated by technical moderator')
      await refresh()
    } catch (e: any) {
      setErrorMessage(e?.response?.data?.detail || 'Failed to update meeting link.')
    } finally {
      setBusyId(null)
    }
  }

  const handleTechnicalCheck = async (seminarId: string) => {
    setBusyId(seminarId)
    setErrorMessage('')
    try {
      await workflowService.createTechnicalCheck(seminarId, {
        latex_compatible: Boolean(latexCompatibleById[seminarId] ?? false),
        hybrid_status: hybridStatusById[seminarId],
        meeting_link_valid: Boolean((meetingLinkById[seminarId] ?? '').trim())
      })
      await refresh()
    } catch (e: any) {
      setErrorMessage(e?.response?.data?.detail || 'Technical check failed.')
    } finally {
      setBusyId(null)
    }
  }

  const handleStartSession = async (seminarId: string) => {
    setBusyId(seminarId)
    setErrorMessage('')
    try {
      const meetingLink = meetingLinkById[seminarId] ?? ''
      await workflowService.startSession(seminarId, meetingLink)
      await refresh()
    } catch (e: any) {
      setErrorMessage(e?.response?.data?.detail || 'Failed to start session.')
    } finally {
      setBusyId(null)
    }
  }

  const handleUploadMaterials = async (seminarId: string) => {
    const file_url = materialsUrlById[seminarId] ?? ''
    if (!file_url.trim()) {
      setErrorMessage('file_url is required.')
      return
    }
    setBusyId(seminarId)
    setErrorMessage('')
    try {
      await workflowService.uploadTechnicalMaterials(seminarId, file_url.trim())
      await refresh()
    } catch (e: any) {
      setErrorMessage(e?.response?.data?.detail || 'Failed to upload materials.')
    } finally {
      setBusyId(null)
    }
  }

  const handleReportIssue = async (seminarId: string) => {
    const issue_type = (issueTypeById[seminarId] ?? 'OTHER').trim()
    const description = issueDescriptionById[seminarId] ?? ''
    if (!description.trim()) {
      setErrorMessage('Issue description is required.')
      return
    }
    setBusyId(seminarId)
    setErrorMessage('')
    try {
      await workflowService.reportTechnicalIssue(seminarId, issue_type, description, false)
      await refresh()
    } catch (e: any) {
      setErrorMessage(e?.response?.data?.detail || 'Failed to report technical issue.')
    } finally {
      setBusyId(null)
    }
  }

  return (
    <AppLayout title="Technical Moderator Dashboard" subtitle="Session execution support: meeting links, LaTeX compatibility, hybrid status.">
      {errorMessage && <div className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{errorMessage}</div>}
      {loading ? (
        <div className="rounded-lg bg-white p-5 shadow-sm">Loading…</div>
      ) : (
        <>
          <div className="rounded-lg bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <h2 className="font-semibold text-gray-900">🎥 Today’s Sessions</h2>
              <span className="rounded bg-gray-100 px-2 py-1 text-xs text-gray-700">
                {data?.todays_sessions?.count ?? 0} session(s)
              </span>
            </div>
            <div className="mt-4 space-y-3">
              {sessions.length === 0 && <div className="text-sm text-gray-600">No sessions assigned to you for today.</div>}
              {sessions.map((s) => {
                const linkOk = s.meeting_link_valid ?? false
                return (
                  <div key={s.id} className="rounded border border-gray-100 p-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <div>
                        <div className="font-medium text-gray-900">{s.title}</div>
                        <div className="mt-1 text-xs text-gray-600">{new Date(s.scheduled_date).toLocaleString()}</div>
                      </div>
                      <span className={`rounded px-2 py-1 text-xs ${linkOk ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}`}>
                        {linkOk ? 'Link Ready' : 'Link Needs Setup'}
                      </span>
                    </div>

                    <div className="mt-3 grid gap-3 md:grid-cols-2">
                      <div>
                        <label className="block text-xs text-gray-600">Meeting link</label>
                        <input
                          className="mt-1 w-full rounded border px-3 py-2 text-sm"
                          placeholder="Paste meeting link"
                          value={meetingLinkById[s.id] ?? (s.meeting_link ?? '')}
                          onChange={(e) => setMeetingLinkById((prev) => ({ ...prev, [s.id]: e.target.value }))}
                        />
                      </div>
                      <div>
                        <label className="block text-xs text-gray-600">Hybrid session status</label>
                        <input
                          className="mt-1 w-full rounded border px-3 py-2 text-sm"
                          placeholder="e.g. READY / NEEDS_ATTENTION"
                          value={hybridStatusById[s.id] ?? (s.hybrid_status ?? '')}
                          onChange={(e) => setHybridStatusById((prev) => ({ ...prev, [s.id]: e.target.value }))}
                        />
                      </div>
                    </div>

                    <div className="mt-2 flex flex-wrap gap-2">
                      <button
                        className="rounded bg-green-600 px-3 py-2 text-sm text-white hover:bg-green-700 disabled:opacity-50"
                        disabled={busyId === s.id}
                        onClick={() => handleMeetingLink(s.id)}
                      >
                        Generate Meeting Link
                      </button>
                      <button
                        className="rounded bg-blue-600 px-3 py-2 text-sm text-white hover:bg-blue-700 disabled:opacity-50"
                        disabled={busyId === s.id}
                        onClick={() => handleTechnicalCheck(s.id)}
                      >
                        System/LaTeX Compatibility Check
                      </button>
                    </div>

                    <div className="mt-3 flex flex-wrap gap-2">
                      <button
                        className="rounded bg-amber-600 px-3 py-2 text-sm text-white hover:bg-amber-700 disabled:opacity-50"
                        disabled={busyId === s.id}
                        onClick={() => handleStartSession(s.id)}
                      >
                        Start Session
                      </button>
                    </div>

                    <div className="mt-3 grid gap-3 md:grid-cols-2">
                      <div>
                        <label className="block text-xs text-gray-600">Session material file_url</label>
                        <input
                          className="mt-1 w-full rounded border px-3 py-2 text-sm"
                          placeholder="e.g. https://.../slides.pdf"
                          value={materialsUrlById[s.id] ?? ''}
                          onChange={(e) => setMaterialsUrlById((prev) => ({ ...prev, [s.id]: e.target.value }))}
                        />
                      </div>
                      <div>
                        <label className="block text-xs text-gray-600">Technical issue type</label>
                        <input
                          className="mt-1 w-full rounded border px-3 py-2 text-sm"
                          placeholder="LATEX / AUDIO / HYBRID / OTHER"
                          value={issueTypeById[s.id] ?? ''}
                          onChange={(e) => setIssueTypeById((prev) => ({ ...prev, [s.id]: e.target.value }))}
                        />
                      </div>
                    </div>

                    <div className="mt-2">
                      <label className="block text-xs text-gray-600">Technical issue description</label>
                      <textarea
                        className="mt-1 w-full rounded border px-3 py-2 text-sm"
                        rows={2}
                        placeholder="What went wrong? What do you need?"
                        value={issueDescriptionById[s.id] ?? ''}
                        onChange={(e) => setIssueDescriptionById((prev) => ({ ...prev, [s.id]: e.target.value }))}
                      />
                    </div>

                    <div className="mt-3 flex flex-wrap gap-2">
                      <button
                        className="rounded bg-green-700 px-3 py-2 text-sm text-white hover:bg-green-800 disabled:opacity-50"
                        disabled={busyId === s.id}
                        onClick={() => handleUploadMaterials(s.id)}
                      >
                        Upload Session Materials
                      </button>
                      <button
                        className="rounded bg-red-600 px-3 py-2 text-sm text-white hover:bg-red-700 disabled:opacity-50"
                        disabled={busyId === s.id}
                        onClick={() => handleReportIssue(s.id)}
                      >
                        Report Technical Issue
                      </button>
                    </div>

                    <div className="mt-3 flex items-center gap-2">
                      <input
                        id={`latex-${s.id}`}
                        type="checkbox"
                        checked={Boolean(latexCompatibleById[s.id] ?? s.latex_compatible ?? false)}
                        onChange={(e) => setLatexCompatibleById((prev) => ({ ...prev, [s.id]: e.target.checked }))}
                      />
                      <label htmlFor={`latex-${s.id}`} className="text-sm text-gray-700">
                        LaTeX compatible
                      </label>
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        </>
      )}
    </AppLayout>
  )
}

export default TechnicalModeratorDashboard

